[project]
name = "backend"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.114.2",
    "langchain-google-genai>=2.0.0",
    "python-multipart>=0.0.9",
    "uvicorn>=0.30.6",
]

[tool.ruff]
extend = "../pyproject.toml"
